### ISSUE TITLE
rabbitmq version for aiida 2.0 in aiida docker image

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-prerequisites#39]
ubuntu 20.04 ships with rabbitmq 3.8.2 which leads to

```
Warning: RabbitMQ v3.8.2 is not supported and will cause unexpected problems!
Warning: It can cause long-running workflows to crash and jobs to be submitted multiple times.
Warning: See https://github.com/aiidateam/aiida-core/wiki/RabbitMQ-version-to-use for details.
``` 

So, we now need to decide whether to use an old version of rabbitmq or a new version with proper configuration.

I'm leaning towards the latter solution (otherwise we're stuck with an old version for which there is no maintenance).

I think the [corresponding section of the wiki](https://github.com/aiidateam/aiida-core/wiki/RabbitMQ-version-to-use#using-a-recent-rabbitmq-version) should mention (1) which configuration values to change, and whether (2) one still needs to remove some temporary files or not.

It should also include instructions on how to disable the warning once rabbitmq has been configured correctly.

Thoughts @chrisjsewell @giovannipizzi @csadorf ?

**Comment by csadorf** [comment]
If we can automatically configure RabbitMQ on the docker image to work-around the current limitation, I think that would be a viable stop-gap solution.

**Comment by yakutovicha** [comment]
I think we should install RabbitMQ into a separate conda environment, as for PGSQL (see #49). That should simplify the management of package versions.
