### ISSUE TITLE
Have old and new versions of the PostgreSQL database installed in the container

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#42]
As a developer, I need to have both versions of the database to perform the automatic migration safely.

**Comment by csadorf** [comment]
I think this would be most easily achieved with a dedicated conda environment:

```
conda create -n pgsql10 postgresql=10
```

**Comment by yakutovicha** [comment]
I am going to close this since I am planning to create a temporary conda environment for the migration. The environment is going to be deleted as soon as the migration is done.
