### ISSUE TITLE
[INVALID] Can't create a new conda environment while being login as `aiida` user

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#45]
The `aiida` user must be able to create conda environments.

To my understanding, the bug was introduced in #38 by removing the following lines from the `Dockerfile`:

```python
# This is needed to let non-root users create conda environments.
RUN touch /opt/conda/pkgs/urls.txt
```

@unkcpz do you remember the reason behind this removal? Just in case I am missing something.

**Comment by unkcpz** [comment]
https://github.com/aiidateam/aiida-prerequisites/blob/e2cb28b8ce1f68c8260f65b1310c8b5bb60fb4ef/my_init.d/create-system-user.sh#L17-L18

This is added to explicitly give the permission to the conda folder. I think I checked and test this and it works.

**Comment by unkcpz** [comment]
> The aiida user must be able to create conda environments.

Ah, you mean create the conda environment. This I did not check. After I remove `RUN touch /opt/conda/pkgs/urls.txt` without add `chown ${SYSTEM_USER}:${SYSTEM_USER} ${CONDA_DIR} ` there is an error message about https://github.com/conda/conda/issues/7267

**Comment by yakutovicha** [comment]
> > The aiida user must be able to create conda environments.
> 
> Ah, you mean create the conda environment. This I did not check. After I remove `RUN touch /opt/conda/pkgs/urls.txt` without add `chown ${SYSTEM_USER}:${SYSTEM_USER} ${CONDA_DIR} ` there is an error message about [conda/conda#7267](https://github.com/conda/conda/issues/7267)

Sorry, I was wrong. I just tested the 0.5.0 version of the image. The `aiida` user **can** create a new Conda environment. Sorry for the confusion.
