### ISSUE TITLE
Install PostgreSQL into a separate conda environment.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#48]
As the developer, I would like to allow the flexibility to install different versions of PostgreSQL into the same container. In the current approach, we are bound to what is available in the selected Ubuntu release. Things become even more tricky when we want to migrate the database to a newer version of PostgreSQL - it requires both (old and new) versions to be installed in the system at the same time.

Having the PostgreSQL installed in a separated conda environment should allow us both: to install any version of PostgreSQL and as many of those as one desires.

**Comment by csadorf** [comment]
@yakutovicha Is this required for #44 ?

**Comment by yakutovicha** [comment]
> @yakutovicha Is this required for #44 ?

Yep, that is a prerequisite. Thanks!
